export const images = [
  {img:"01.jpg", class_name:'slower'},
  {img:"02.jpg", class_name:'faster'},
  {img:"03.jpg", class_name:'slower vertical'},
  {img:"04.jpg", class_name:'slower slower-down'},
  {img:"05.jpg", class_name:'faster1'},
  {img:"06.jpg", class_name:'slower slower2'},
  {img:"01.jpg", class_name:'slower'},
  {img:"02.jpg", class_name:'faster'},
  {img:"03.jpg", class_name:'slower vertical'},
  {img:"04.jpg", class_name:'slower slower-down'},
  {img:"05.jpg", class_name:'fastest faster1'},
  {img:"06.jpg", class_name:'slower slower2'},
  {img:"07.jpg", class_name:'slower last'},
];
